name: Test build

on:
  push:
    branch: main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v14
      with:
        nix_path: nixpkgs=channel:nixos-21.05

    - run: nix-build

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        path: nextcloud_*.raw*
        if-no-files-found: error
