name: Test build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ARTIFACT_NAME: nextcloud_test

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v14
      with:
        nix_path: nixpkgs=channel:nixos-21.05

    - run: nix-build

    - name: Prepare artifact
      run: cp result ${{ env.ARTIFACT_NAME }}.raw

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_NAME }}.raw
        if-no-files-found: error
        retention-days: 5
