name: Test build & release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v30

    - run: nix build --no-update-lock-file
    - run: nix flake check --no-update-lock-file

    - name: Prepare artifacts
      run: |
        cp result/*.raw ./
        sh -c 'sha256sum $0 > $0.sha256' *.raw

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        retention-days: 5
        path: |
          *.raw
          *.raw.sha256

    - name: Release Info
      run: |
        nix build --no-update-lock-file -o release-info .#release-info
        cat release-info

    - name: Create a github release from tag
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        files: |
          *.raw
          *.raw.sha256
        body_path: release-info
