name: Flake update

on: workflow_dispatch

jobs:
  flake-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
    - run: nix flake update
    - run: nix build --no-update-lock-file .#release-info

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "[Automated] update flake"
        commit-message: "[Automated] update flake"
        branch: "auto/flake-update"
        add-paths: flake.lock
        delete-branch: true
        labels: |
            automated pr
        body-path: result
