name: Make a release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11

    - run: nix-build

    - name: Prepare release files
      run: |
        cp result nextcloud_${GITHUB_REF#refs/tags/}.raw
        sha256sum nextcloud_${GITHUB_REF#refs/tags/}.raw > nextcloud_${GITHUB_REF#refs/tags/}.raw.sha256

    - name: Create a github release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        files: nextcloud_*.raw*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
